import type { Metadata } from "next";
import { Inter, Manrope } from 'next/font/google'
import "./globals.css";
import { getLatestBlock, getNumBlocksPerSession } from '@/api/blocks'
import getPrice from '@/api/price'
import { headers } from 'next/headers'
import getMetadata from '@/api/metadata'
import ReactQueryProvider from '@/context/query'
import { ApolloWrapper } from '@/config/apollo/client'
import HeightContextProvider from '@/context/height'
import AppBar from '@/AppBar/AppBar'
import { Times } from '@/utils/dates'

const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const manrope = Manrope({
  variable: '--font-manrope',
  weight: ['400', '500', '700'],
  style: ['normal',],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "POKT Money",
  // TODO: Add description
  // description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [
    latestBlock,
    blocksPerSession,
    price,
    metadata,
  ] = await Promise.all([
    getLatestBlock().catch(() => null),
    getNumBlocksPerSession().catch(() => 0),
    getPrice(),
    getMetadata().catch(() => null),
  ])



  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased`}
      >
        <ReactQueryProvider initialPriceData={price}>
          <ApolloWrapper url={process.env.INDEXER_API_URL!}>
            <HeightContextProvider
              firstHeight={latestBlock?.id}
              networkHeight={metadata?._metadata?.targetHeight || 0}
              blocksPerSession={blocksPerSession}
              // the timestamp is in UTC, so we need to add the Z to the end because the api doesn't include it
              firstTime={latestBlock?.timestamp ? latestBlock.timestamp + 'Z' : ''}
            >
              {children}
            </HeightContextProvider>
          </ApolloWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
